Repository Data-Science-Community-SRM/dsc-recruitment-portal, pull requests merged in 2024-09, with the labels that each got.

#38 feat: Fix V1 For Bugs and Maintainance of Site
  client/src/app/page.tsx
  client/src/components/domains/lightbox.tsx
  client/src/components/home/domain-cards.tsx
  client/src/components/home/header.tsx
  client/src/components/home/hero.tsx
Labels: bug, backend, frontend

#41 Google sheets integration
  server/.env.example
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/api/corporate/corporate.schema.ts
  server/src/api/corporate/corporate.services.ts
  server/src/api/creative/creative.schema.ts
  server/src/api/creative/creative.services.ts
  server/src/api/research/research.schema.ts
  server/src/api/research/research.services.ts
  server/src/api/technical/technical.schema.ts
  server/src/api/technical/technical.services.ts
  server/src/config/index.ts
  server/src/loaders/gKeys.ts
  server/src/loaders/index.ts
  server/src/shared/utils/confirm.ts
  server/src/shared/utils/sheets.ts
  server/src/shared/utils/titleCase.ts
Labels: enhancement, backend

#42 Feat: Fixed apply now and Added Logic
  client/src/components/domains/lightbox.tsx
  client/src/components/domainsections/domain.tsx
  client/src/components/home/domain-cards.tsx
  client/src/components/home/header.tsx
Labels: frontend

#43 feat: Connection added for Forms & logic Applied
  client/src/components/domains/form.tsx
  client/src/components/domains/lightbox.tsx
Labels: backend

#44 Form fixes
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/app/layout.tsx
  client/src/components/domains/form.tsx
  client/src/components/ui/toast.tsx
  client/src/components/ui/toaster.tsx
  client/src/hooks/use-toast.ts
  client/src/lib/submitAction.ts
Labels: bug, frontend

#45 Fix V1.5: Bug Fix and Mobile Optimization
  client/src/components/home/header.tsx
Labels: frontend

#47 Success message for submissions
  client/src/components/domains/form.tsx
  client/src/components/domains/lightbox.tsx
  server/src/api/index.ts
Labels: enhancement, frontend

#48 Feat: Added Mobile Optimization & Gradient in apply now
  client/src/components/home/domain-cards.tsx
  client/src/components/home/header.tsx
Labels: frontend

#50 Feat : Fixed Lightbox
  client/src/components/domains/lightbox.tsx
Labels: frontend

#54 Feat: Optimization and Fixes
  client/src/app/favicon.ico
  client/src/app/layout.tsx
  client/src/app/page.tsx
Labels: bug, frontend

#56 Next.js Cache Poisoning Fixed
  client/package-lock.json
  client/package.json
Labels: security risk
